# Generated by Django 5.2.7 on 2025-10-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
