# Generated by Django 5.2.7 on 2025-10-13 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=255, verbose_name='Название')),
                ('price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость курса')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение для превью курса', null=True, upload_to='courses/previews/', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Введите подробное описание курса', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название урока', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Введите подробное описание урока', verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение для превью урока', null=True, upload_to='lessons/previews/', verbose_name='Превью')),
                ('video_url', models.URLField(blank=True, help_text='Вставьте ссылку на видеоурок', verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-subscription_date'],
            },
        ),
    ]
