# Generated by Django 5.2.7 on 2025-10-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0002_2_10"),
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Стоимость курса",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_price",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course",
                to="djstripe.price",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course",
                to="djstripe.product",
            ),
        ),
    ]
